### ISSUE TITLE
which LCD I2C library to use ?

### ISSUE THREAD

**Issue by fred2088** [reven/Light-painter#1]
"tick" and custom characters are not defined from default LCD i2C library  ?

**Comment by reven** [comment]
The library is defined in the code, at the beginning of the sketch:
```
#include <LiquidCrystal_I2C.h>
```
The custom characters (hourglass, check, etc) are defined in chars.h and are pushed to the LCD with the `setup_chars()` function. Normally libraries don't define these types of characters; the LCDs use a specific character set that allows 8 custom chars.

**Comment by fred2088** [comment]
find the chars.h and is already include, but only the symbol -> from OK can display on LCD,
the symbol from Ready , No, Yes can't display correctly ?

**Comment by fred2088** [comment]
temp workaround ...
change the "static const PROGMEM char"  to "uint8"_t from chars.h

Thanks

**Comment by reven** [comment]
This is a very bad workaround as `static const PROGMEM char` puts the values in flash memory while having them defined as `uint8_t` puts them in SRAM and takes away memory from sketch execution. Do you have the latest version of the IDE? The static PROGMEM declaration shouldn't have any issue in version 1.8.5.

**Comment by fred2088** [comment]
all lastest, can't display custom char if using static const PROGMEM char ... only work if changed to uint8_t

using arduino nano :p

**Comment by reven** [comment]
I'm sorry Fred, I can't reproduce this bug. I'll try with a nano and see if there are issues with my code, but I won't be able to get on it until 4 or 5 days.

I'll reopen the issue, but just to be 100% sure and not chase white rabbits, can you please double check and make sure that your IDE is version 1.8.5 and that the nano that you are using is a ATmega328P based one (the one with 1kb EEPROM, 2kB SRAM and 32kB Flash).

I'm not aware of any differences between PROGMEM between the Uno and the Nano, but I'll double check that my code works on it.

**Comment by reven** [comment]
So I had a few hours and tried my code on a Nano and everything works as expected. All custom characters display correctly. I'm using version 1.1.4 of the LiquidCrystal_I2C library.

Unfortunately, without more info I can't really trouble shoot this, but it doesn't seem likely that this is a bug with the code or anything strange happening on the Nano.

The reason I insist so much on your IDE version is because there have been changes to how the avr gcc interprets PROGMEM statements. Try eliminating the `const` keyword; if that works your IDE is older than 1.8.5.

I will reopen if you can provide more data or debug the issue.
